# Generated by Django 2.2.4 on 2021-10-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tBT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='company',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='form',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='form',
            name='manager',
        ),
    ]
