# Generated by Django 3.1.4 on 2021-02-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
